/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IndexRouteImport } from './routes/index'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/automations': typeof AutomationsRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/properties': typeof PropertiesRoute
  '/reports': typeof ReportsRoute
  '/tickets': typeof TicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/automations': typeof AutomationsRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/properties': typeof PropertiesRoute
  '/reports': typeof ReportsRoute
  '/tickets': typeof TicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/automations': typeof AutomationsRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/properties': typeof PropertiesRoute
  '/reports': typeof ReportsRoute
  '/tickets': typeof TicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/audit-logs'
    | '/automations'
    | '/calendar'
    | '/login'
    | '/memory'
    | '/properties'
    | '/reports'
    | '/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/audit-logs'
    | '/automations'
    | '/calendar'
    | '/login'
    | '/memory'
    | '/properties'
    | '/reports'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/audit-logs'
    | '/automations'
    | '/calendar'
    | '/login'
    | '/memory'
    | '/properties'
    | '/reports'
    | '/tickets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditLogsRoute: typeof AuditLogsRoute
  AutomationsRoute: typeof AutomationsRoute
  CalendarRoute: typeof CalendarRoute
  LoginRoute: typeof LoginRoute
  MemoryRoute: typeof MemoryRoute
  PropertiesRoute: typeof PropertiesRoute
  ReportsRoute: typeof ReportsRoute
  TicketsRoute: typeof TicketsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditLogsRoute: AuditLogsRoute,
  AutomationsRoute: AutomationsRoute,
  CalendarRoute: CalendarRoute,
  LoginRoute: LoginRoute,
  MemoryRoute: MemoryRoute,
  PropertiesRoute: PropertiesRoute,
  ReportsRoute: ReportsRoute,
  TicketsRoute: TicketsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
